---
title: "Gender Inequalities in Campaign Finance"
output:
  pdf_document: default
  html_document: default
header-includes:
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancypagestyle{plain}{\pagestyle{fancy}}
  - \fancyhead[L]{}
  - \fancyhead[C]{This material should not be shared beyond those who are enrolled in this class}
---

In the United States, political fundraising is crucial to
the success and eventual election of politicians. Female politicians, 
however, report more fundraising difficulties than their 
male counterparts. Female politicians are also underrepresented in 
state legislatures across the country. In this exercise, we investigate 
the presence of potential gender inequalities in 
campaign finance.

This exercise is in part based on:
 Barber, Michael, Daniel Butler, and Jessica Preece. 2016. "[Gender Inequalities in Campaign
 Finance.](http://dx.doi.org/10.1561/100.00015126)" *Quarterly Journal 
 of Political Science* 11(2): 219-248.
 
In this paper, the authors attempt to estimate whether female state 
legislative incumbents have more trouble fundraising than do male 
legislative incumbents. Observations consists of information on all U.S. 
state legislative races in which a male and female candidate ran 
against each other. The data include their winning margin and their 
current-cycle fundraising. To mitigate concerns about omitted variable 
bias (women may run in districts that are fundamentally different than 
districts in which men are the incumbents), the researchers use a 
variation of a *regression discontinuity design (RDD)*. As with studies of the 
incumbency effect, the authors argue that those who barely won last 
cycle won at random, given the closeness of the previous election.

We will analyze their data to help determine if male candidates raise 
more money than female candidates. 

The data file you will use is `BBP2016_Data.csv`, a CSV data file. 
The file contains the following variables, which we will make use of in 
this exercise, as well as other variables that the authors made 
use of in their paper:

--------------------------------------------------------------------------------
 Name                     Description
 -----------------------  ------------------------------------------------------
 `bonica.rid`             Candidate ID number

 `cycle`                  Year in which the election was held

 `name`                   Legislator's name
 
 `cand.gender`            Legislator's gender

 `Party`                  Party affiliation (Democrat = 100, Republican = 200)

 `seat`                   Whether the legislator ran for upper or lower house

 `running.variable`       Male candidate vote share minus female candidate vote share in previous election

 `total.raised.candidate` Total funding raised by legislator after winning election

 `male.money`             Total raised from male donors

 `female.money`           Total raised from female donors
 
 `share.district.total`   Proportion of total district funding raised by the incumbent
 -------------------------------------------------------------------------------

## Question 1

How many observations are included in this dataset? What is the 
  gender composition of the candidates contained in this 
  dataset? What is the party composition? What election cycles are 
  included? Are the number of observations in each cycle increasing or 
  decreasing over time?  Give a brief substantive interpretation 
  of the results.
   
## Question 2

Compare the party composition of female candidates and of male candidates. 
  What proportion of Democratic candidates are male? Female? What proportion 
  of Republican candidates are male? Female? Briefly comment on the results.

## Question 3

Next, we start looking at fundraising, our outcome of primary interest. 
  What is the mean amount of funding raised by female candidates? 
  And male candidates? What is the difference in these means? Do males or 
  females raise more money, on average? Briefly comment on the results.

## Question 4

Plot the density of the funding raised by male and female candidates, 
  making sure to have an upper limit of 2,000,000. Use a red line for 
  female candidates and blue for male candidates. Add red and blue 
  dashed lines at the mean for women and men. Provide a substantive 
  interpretation of the results.
  
## Question 5

One problem with comparing fundraising among male and female incumbents 
  is that they may run in very different types of districts. In order to 
  estimate a gender effect, we are going to look at candidates who won in 
  close races, where `running.variable` is within 1 percentage point of zero.
  For what values of `running.variable` did the male candidate win by 1 
  percentage points or less? For what values of `running.variable` did 
  the female candidate win by 1 percentage point or less? Use these results 
  to subset the data into two data frames: close races where the female won in the 
  last election and close races where the male won in the last election. (You 
  can use either < and > or <= and =>.) How many observations are in each subset?
  If we took the mean difference between female and male fundraising in
  these new subsets, would we get a causal effect? Why or why not?
  
## Question 6
 
Estimate the average causal effect of gender on fundraising by regressing 
  `log.total.raised.candidate` on `running.variable` in each of the newly 
  created subsets and then taking the difference in predicted outcomes 
  at the discontinuity (i.e., `running.variable = 0`). Express the 
  causal effect in dollars (as opposed to log dollars). Give brief substantive 
  comments on the viability of this estimate as a causal effect, as well as
  its internal and external validity.
  
## Question 6

Visualize the analysis in Question 5 by plotting data points and  
  fitted regression lines. Briefly comment on the plot.
  
## Question 7

A key concern in this design is how we designate a "bandwidth," or 
  how far from zero we look with our running variable when we fit our
  regression. In the previous question, we took a bandwidth of 1 
  percentage point. Repeat calculations for the difference in predicted
  outcomes at the discontuinity using bandwidths of 2, 1, 0.5, 0.25, 
  and 0.1. Do the results change as you vary the bandwidth? If so, why?
  Briefly comment on the results.
  
## Question 8

Last, we look at patterns attributable to the gender of the donors. Maintain
  the 1% bandwidth in the running variable that was used above, 
  and compare the donations by female donors and by male donors to 
  candidates at the discontinuity, respectively. Comment on the results.
  
